class Autogenerated {
  String? type;
  List<Data>? data;

  Autogenerated({this.type, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    type = json['type'];

    data = <Data>[];
    json['data'].forEach((v) {
      data!.add(new Data.fromJson(v));
    });
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['type'] = this.type;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String? title;
  String? song;
  Track? track;
  String? bitrate;
  String? server;
  String? autodj;
  String? source;
  bool? offline;
  String? summary;
  int? listeners;
  int? maxlisteners;
  int? reseller;
  bool? serverstate;
  bool? sourcestate;
  bool? sourceconn;
  String? date;
  String? time;
  String? rawmeta;
  String? mountpoint;
  String? tuneinurl;
  String? tuneinurltls;
  String? directtuneinurl;
  String? proxytuneinurl;
  String? proxytuneinurltls;
  String? tuneinformat;
  String? webplayer;
  String? servertype;
  int? listenertotal;
  String? url;

  Data(
      {this.title,
      this.song,
      this.track,
      this.bitrate,
      this.server,
      this.autodj,
      this.source,
      this.offline,
      this.summary,
      this.listeners,
      this.maxlisteners,
      this.reseller,
      this.serverstate,
      this.sourcestate,
      this.sourceconn,
      this.date,
      this.time,
      this.rawmeta,
      this.mountpoint,
      this.tuneinurl,
      this.tuneinurltls,
      this.directtuneinurl,
      this.proxytuneinurl,
      this.proxytuneinurltls,
      this.tuneinformat,
      this.webplayer,
      this.servertype,
      this.listenertotal,
      this.url});

  Data.fromJson(Map<String, dynamic> json) {
    title = json['title'];
    song = json['song'];
    track = json['track'] != null ? new Track.fromJson(json['track']) : null;
    bitrate = json['bitrate'];
    server = json['server'];
    autodj = json['autodj'];
    source = json['source'];
    offline = json['offline'];
    summary = json['summary'];
    listeners = json['listeners'];
    maxlisteners = json['maxlisteners'];
    reseller = json['reseller'];
    serverstate = json['serverstate'];
    sourcestate = json['sourcestate'];
    sourceconn = json['sourceconn'];
    date = json['date'];
    time = json['time'];
    rawmeta = json['rawmeta'];
    mountpoint = json['mountpoint'];
    tuneinurl = json['tuneinurl'];
    tuneinurltls = json['tuneinurltls'];
    directtuneinurl = json['directtuneinurl'];
    proxytuneinurl = json['proxytuneinurl'];
    proxytuneinurltls = json['proxytuneinurltls'];
    tuneinformat = json['tuneinformat'];
    webplayer = json['webplayer'];
    servertype = json['servertype'];
    listenertotal = json['listenertotal'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['title'] = this.title;
    data['song'] = this.song;
    if (this.track != null) {
      data['track'] = this.track!.toJson();
    }
    data['bitrate'] = this.bitrate;
    data['server'] = this.server;
    data['autodj'] = this.autodj;
    data['source'] = this.source;
    data['offline'] = this.offline;
    data['summary'] = this.summary;
    data['listeners'] = this.listeners;
    data['maxlisteners'] = this.maxlisteners;
    data['reseller'] = this.reseller;
    data['serverstate'] = this.serverstate;
    data['sourcestate'] = this.sourcestate;
    data['sourceconn'] = this.sourceconn;
    data['date'] = this.date;
    data['time'] = this.time;
    data['rawmeta'] = this.rawmeta;
    data['mountpoint'] = this.mountpoint;
    data['tuneinurl'] = this.tuneinurl;
    data['tuneinurltls'] = this.tuneinurltls;
    data['directtuneinurl'] = this.directtuneinurl;
    data['proxytuneinurl'] = this.proxytuneinurl;
    data['proxytuneinurltls'] = this.proxytuneinurltls;
    data['tuneinformat'] = this.tuneinformat;
    data['webplayer'] = this.webplayer;
    data['servertype'] = this.servertype;
    data['listenertotal'] = this.listenertotal;
    data['url'] = this.url;
    return data;
  }
}

class Track {
  String? artist;
  String? title;
  String? album;
  int? royaltytrackid;
  Null? started;
  int? id;
  int? length;
  Playlist? playlist;
  String? buyurl;
  String? imageurl;

  Track(
      {this.artist,
      this.title,
      this.album,
      this.royaltytrackid,
      this.started,
      this.id,
      this.length,
      this.playlist,
      this.buyurl,
      this.imageurl});

  Track.fromJson(Map<String, dynamic> json) {
    artist = json['artist'];
    title = json['title'];
    album = json['album'];
    royaltytrackid = json['royaltytrackid'];
    started = json['started'];
    id = json['id'];
    length = json['length'];
    playlist = json['playlist'] != null
        ? new Playlist.fromJson(json['playlist'])
        : null;
    buyurl = json['buyurl'];
    imageurl = json['imageurl'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['artist'] = this.artist;
    data['title'] = this.title;
    data['album'] = this.album;
    data['royaltytrackid'] = this.royaltytrackid;
    data['started'] = this.started;
    data['id'] = this.id;
    data['length'] = this.length;
    if (this.playlist != null) {
      data['playlist'] = this.playlist!.toJson();
    }
    data['buyurl'] = this.buyurl;
    data['imageurl'] = this.imageurl;
    return data;
  }
}

class Playlist {
  int? id;
  String? title;

  Playlist({this.id, this.title});

  Playlist.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    return data;
  }
}
