import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:http/http.dart' as http;
import '../Album.dart';

class Data_provider with ChangeNotifier {
  late Future<Autogenerated> album = FetchAlbum();
  late AsyncSnapshot<Autogenerated> snapshot;

  Future<Autogenerated> FetchAlbum() async {
    final _response = await http.get(Uri.parse(
        "http://cast1.asurahosting.com:2199/rpc/ahanghaa/streaminfo.get"));
    if (_response.statusCode == 200)
      return Autogenerated.fromJson(jsonDecode(_response.body));
    else
      throw Exception("error");
  }

  void set(AsyncSnapshot<Autogenerated> s) {
    snapshot = s;
    notifyListeners();
  }

  Future<void> refresh() async {
    return Future.delayed(const Duration(seconds: 2), () {
      album = FetchAlbum();
      print("object");
      notifyListeners();
      refresh();
    });
  }
}
